// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/cms-middleware/pkg/db/ent/category"
	"github.com/google/uuid"
)

// CategoryCreate is the builder for creating a Category entity.
type CategoryCreate struct {
	config
	mutation *CategoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (cc *CategoryCreate) SetCreatedAt(u uint32) *CategoryCreate {
	cc.mutation.SetCreatedAt(u)
	return cc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cc *CategoryCreate) SetNillableCreatedAt(u *uint32) *CategoryCreate {
	if u != nil {
		cc.SetCreatedAt(*u)
	}
	return cc
}

// SetUpdatedAt sets the "updated_at" field.
func (cc *CategoryCreate) SetUpdatedAt(u uint32) *CategoryCreate {
	cc.mutation.SetUpdatedAt(u)
	return cc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cc *CategoryCreate) SetNillableUpdatedAt(u *uint32) *CategoryCreate {
	if u != nil {
		cc.SetUpdatedAt(*u)
	}
	return cc
}

// SetDeletedAt sets the "deleted_at" field.
func (cc *CategoryCreate) SetDeletedAt(u uint32) *CategoryCreate {
	cc.mutation.SetDeletedAt(u)
	return cc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (cc *CategoryCreate) SetNillableDeletedAt(u *uint32) *CategoryCreate {
	if u != nil {
		cc.SetDeletedAt(*u)
	}
	return cc
}

// SetEntID sets the "ent_id" field.
func (cc *CategoryCreate) SetEntID(u uuid.UUID) *CategoryCreate {
	cc.mutation.SetEntID(u)
	return cc
}

// SetNillableEntID sets the "ent_id" field if the given value is not nil.
func (cc *CategoryCreate) SetNillableEntID(u *uuid.UUID) *CategoryCreate {
	if u != nil {
		cc.SetEntID(*u)
	}
	return cc
}

// SetAppID sets the "app_id" field.
func (cc *CategoryCreate) SetAppID(u uuid.UUID) *CategoryCreate {
	cc.mutation.SetAppID(u)
	return cc
}

// SetParentID sets the "parent_id" field.
func (cc *CategoryCreate) SetParentID(u uuid.UUID) *CategoryCreate {
	cc.mutation.SetParentID(u)
	return cc
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (cc *CategoryCreate) SetNillableParentID(u *uuid.UUID) *CategoryCreate {
	if u != nil {
		cc.SetParentID(*u)
	}
	return cc
}

// SetName sets the "name" field.
func (cc *CategoryCreate) SetName(s string) *CategoryCreate {
	cc.mutation.SetName(s)
	return cc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cc *CategoryCreate) SetNillableName(s *string) *CategoryCreate {
	if s != nil {
		cc.SetName(*s)
	}
	return cc
}

// SetSlug sets the "slug" field.
func (cc *CategoryCreate) SetSlug(s string) *CategoryCreate {
	cc.mutation.SetSlug(s)
	return cc
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (cc *CategoryCreate) SetNillableSlug(s *string) *CategoryCreate {
	if s != nil {
		cc.SetSlug(*s)
	}
	return cc
}

// SetEnabled sets the "enabled" field.
func (cc *CategoryCreate) SetEnabled(b bool) *CategoryCreate {
	cc.mutation.SetEnabled(b)
	return cc
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (cc *CategoryCreate) SetNillableEnabled(b *bool) *CategoryCreate {
	if b != nil {
		cc.SetEnabled(*b)
	}
	return cc
}

// SetIndex sets the "index" field.
func (cc *CategoryCreate) SetIndex(u uint32) *CategoryCreate {
	cc.mutation.SetIndex(u)
	return cc
}

// SetNillableIndex sets the "index" field if the given value is not nil.
func (cc *CategoryCreate) SetNillableIndex(u *uint32) *CategoryCreate {
	if u != nil {
		cc.SetIndex(*u)
	}
	return cc
}

// SetID sets the "id" field.
func (cc *CategoryCreate) SetID(u uint32) *CategoryCreate {
	cc.mutation.SetID(u)
	return cc
}

// Mutation returns the CategoryMutation object of the builder.
func (cc *CategoryCreate) Mutation() *CategoryMutation {
	return cc.mutation
}

// Save creates the Category in the database.
func (cc *CategoryCreate) Save(ctx context.Context) (*Category, error) {
	var (
		err  error
		node *Category
	)
	if err := cc.defaults(); err != nil {
		return nil, err
	}
	if len(cc.hooks) == 0 {
		if err = cc.check(); err != nil {
			return nil, err
		}
		node, err = cc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CategoryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cc.check(); err != nil {
				return nil, err
			}
			cc.mutation = mutation
			if node, err = cc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(cc.hooks) - 1; i >= 0; i-- {
			if cc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, cc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Category)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from CategoryMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CategoryCreate) SaveX(ctx context.Context) *Category {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CategoryCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CategoryCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *CategoryCreate) defaults() error {
	if _, ok := cc.mutation.CreatedAt(); !ok {
		if category.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized category.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := category.DefaultCreatedAt()
		cc.mutation.SetCreatedAt(v)
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		if category.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized category.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := category.DefaultUpdatedAt()
		cc.mutation.SetUpdatedAt(v)
	}
	if _, ok := cc.mutation.DeletedAt(); !ok {
		if category.DefaultDeletedAt == nil {
			return fmt.Errorf("ent: uninitialized category.DefaultDeletedAt (forgotten import ent/runtime?)")
		}
		v := category.DefaultDeletedAt()
		cc.mutation.SetDeletedAt(v)
	}
	if _, ok := cc.mutation.EntID(); !ok {
		if category.DefaultEntID == nil {
			return fmt.Errorf("ent: uninitialized category.DefaultEntID (forgotten import ent/runtime?)")
		}
		v := category.DefaultEntID()
		cc.mutation.SetEntID(v)
	}
	if _, ok := cc.mutation.ParentID(); !ok {
		if category.DefaultParentID == nil {
			return fmt.Errorf("ent: uninitialized category.DefaultParentID (forgotten import ent/runtime?)")
		}
		v := category.DefaultParentID()
		cc.mutation.SetParentID(v)
	}
	if _, ok := cc.mutation.Name(); !ok {
		v := category.DefaultName
		cc.mutation.SetName(v)
	}
	if _, ok := cc.mutation.Slug(); !ok {
		v := category.DefaultSlug
		cc.mutation.SetSlug(v)
	}
	if _, ok := cc.mutation.Enabled(); !ok {
		v := category.DefaultEnabled
		cc.mutation.SetEnabled(v)
	}
	if _, ok := cc.mutation.Index(); !ok {
		v := category.DefaultIndex
		cc.mutation.SetIndex(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (cc *CategoryCreate) check() error {
	if _, ok := cc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Category.created_at"`)}
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Category.updated_at"`)}
	}
	if _, ok := cc.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "Category.deleted_at"`)}
	}
	if _, ok := cc.mutation.EntID(); !ok {
		return &ValidationError{Name: "ent_id", err: errors.New(`ent: missing required field "Category.ent_id"`)}
	}
	if _, ok := cc.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "Category.app_id"`)}
	}
	return nil
}

func (cc *CategoryCreate) sqlSave(ctx context.Context) (*Category, error) {
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	return _node, nil
}

func (cc *CategoryCreate) createSpec() (*Category, *sqlgraph.CreateSpec) {
	var (
		_node = &Category{config: cc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: category.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: category.FieldID,
			},
		}
	)
	_spec.OnConflict = cc.conflict
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: category.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := cc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: category.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := cc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: category.FieldDeletedAt,
		})
		_node.DeletedAt = value
	}
	if value, ok := cc.mutation.EntID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: category.FieldEntID,
		})
		_node.EntID = value
	}
	if value, ok := cc.mutation.AppID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: category.FieldAppID,
		})
		_node.AppID = value
	}
	if value, ok := cc.mutation.ParentID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: category.FieldParentID,
		})
		_node.ParentID = value
	}
	if value, ok := cc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: category.FieldName,
		})
		_node.Name = value
	}
	if value, ok := cc.mutation.Slug(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: category.FieldSlug,
		})
		_node.Slug = value
	}
	if value, ok := cc.mutation.Enabled(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: category.FieldEnabled,
		})
		_node.Enabled = value
	}
	if value, ok := cc.mutation.Index(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: category.FieldIndex,
		})
		_node.Index = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Category.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CategoryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (cc *CategoryCreate) OnConflict(opts ...sql.ConflictOption) *CategoryUpsertOne {
	cc.conflict = opts
	return &CategoryUpsertOne{
		create: cc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Category.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (cc *CategoryCreate) OnConflictColumns(columns ...string) *CategoryUpsertOne {
	cc.conflict = append(cc.conflict, sql.ConflictColumns(columns...))
	return &CategoryUpsertOne{
		create: cc,
	}
}

type (
	// CategoryUpsertOne is the builder for "upsert"-ing
	//  one Category node.
	CategoryUpsertOne struct {
		create *CategoryCreate
	}

	// CategoryUpsert is the "OnConflict" setter.
	CategoryUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *CategoryUpsert) SetCreatedAt(v uint32) *CategoryUpsert {
	u.Set(category.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateCreatedAt() *CategoryUpsert {
	u.SetExcluded(category.FieldCreatedAt)
	return u
}

// AddCreatedAt adds v to the "created_at" field.
func (u *CategoryUpsert) AddCreatedAt(v uint32) *CategoryUpsert {
	u.Add(category.FieldCreatedAt, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CategoryUpsert) SetUpdatedAt(v uint32) *CategoryUpsert {
	u.Set(category.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateUpdatedAt() *CategoryUpsert {
	u.SetExcluded(category.FieldUpdatedAt)
	return u
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *CategoryUpsert) AddUpdatedAt(v uint32) *CategoryUpsert {
	u.Add(category.FieldUpdatedAt, v)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CategoryUpsert) SetDeletedAt(v uint32) *CategoryUpsert {
	u.Set(category.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateDeletedAt() *CategoryUpsert {
	u.SetExcluded(category.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *CategoryUpsert) AddDeletedAt(v uint32) *CategoryUpsert {
	u.Add(category.FieldDeletedAt, v)
	return u
}

// SetEntID sets the "ent_id" field.
func (u *CategoryUpsert) SetEntID(v uuid.UUID) *CategoryUpsert {
	u.Set(category.FieldEntID, v)
	return u
}

// UpdateEntID sets the "ent_id" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateEntID() *CategoryUpsert {
	u.SetExcluded(category.FieldEntID)
	return u
}

// SetAppID sets the "app_id" field.
func (u *CategoryUpsert) SetAppID(v uuid.UUID) *CategoryUpsert {
	u.Set(category.FieldAppID, v)
	return u
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateAppID() *CategoryUpsert {
	u.SetExcluded(category.FieldAppID)
	return u
}

// SetParentID sets the "parent_id" field.
func (u *CategoryUpsert) SetParentID(v uuid.UUID) *CategoryUpsert {
	u.Set(category.FieldParentID, v)
	return u
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateParentID() *CategoryUpsert {
	u.SetExcluded(category.FieldParentID)
	return u
}

// ClearParentID clears the value of the "parent_id" field.
func (u *CategoryUpsert) ClearParentID() *CategoryUpsert {
	u.SetNull(category.FieldParentID)
	return u
}

// SetName sets the "name" field.
func (u *CategoryUpsert) SetName(v string) *CategoryUpsert {
	u.Set(category.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateName() *CategoryUpsert {
	u.SetExcluded(category.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *CategoryUpsert) ClearName() *CategoryUpsert {
	u.SetNull(category.FieldName)
	return u
}

// SetSlug sets the "slug" field.
func (u *CategoryUpsert) SetSlug(v string) *CategoryUpsert {
	u.Set(category.FieldSlug, v)
	return u
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateSlug() *CategoryUpsert {
	u.SetExcluded(category.FieldSlug)
	return u
}

// ClearSlug clears the value of the "slug" field.
func (u *CategoryUpsert) ClearSlug() *CategoryUpsert {
	u.SetNull(category.FieldSlug)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *CategoryUpsert) SetEnabled(v bool) *CategoryUpsert {
	u.Set(category.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateEnabled() *CategoryUpsert {
	u.SetExcluded(category.FieldEnabled)
	return u
}

// ClearEnabled clears the value of the "enabled" field.
func (u *CategoryUpsert) ClearEnabled() *CategoryUpsert {
	u.SetNull(category.FieldEnabled)
	return u
}

// SetIndex sets the "index" field.
func (u *CategoryUpsert) SetIndex(v uint32) *CategoryUpsert {
	u.Set(category.FieldIndex, v)
	return u
}

// UpdateIndex sets the "index" field to the value that was provided on create.
func (u *CategoryUpsert) UpdateIndex() *CategoryUpsert {
	u.SetExcluded(category.FieldIndex)
	return u
}

// AddIndex adds v to the "index" field.
func (u *CategoryUpsert) AddIndex(v uint32) *CategoryUpsert {
	u.Add(category.FieldIndex, v)
	return u
}

// ClearIndex clears the value of the "index" field.
func (u *CategoryUpsert) ClearIndex() *CategoryUpsert {
	u.SetNull(category.FieldIndex)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Category.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(category.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *CategoryUpsertOne) UpdateNewValues() *CategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(category.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.Category.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *CategoryUpsertOne) Ignore() *CategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CategoryUpsertOne) DoNothing() *CategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CategoryCreate.OnConflict
// documentation for more info.
func (u *CategoryUpsertOne) Update(set func(*CategoryUpsert)) *CategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CategoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CategoryUpsertOne) SetCreatedAt(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *CategoryUpsertOne) AddCreatedAt(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateCreatedAt() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CategoryUpsertOne) SetUpdatedAt(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *CategoryUpsertOne) AddUpdatedAt(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateUpdatedAt() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CategoryUpsertOne) SetDeletedAt(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *CategoryUpsertOne) AddDeletedAt(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateDeletedAt() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetEntID sets the "ent_id" field.
func (u *CategoryUpsertOne) SetEntID(v uuid.UUID) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetEntID(v)
	})
}

// UpdateEntID sets the "ent_id" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateEntID() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateEntID()
	})
}

// SetAppID sets the "app_id" field.
func (u *CategoryUpsertOne) SetAppID(v uuid.UUID) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateAppID() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateAppID()
	})
}

// SetParentID sets the "parent_id" field.
func (u *CategoryUpsertOne) SetParentID(v uuid.UUID) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateParentID() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateParentID()
	})
}

// ClearParentID clears the value of the "parent_id" field.
func (u *CategoryUpsertOne) ClearParentID() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearParentID()
	})
}

// SetName sets the "name" field.
func (u *CategoryUpsertOne) SetName(v string) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateName() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *CategoryUpsertOne) ClearName() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearName()
	})
}

// SetSlug sets the "slug" field.
func (u *CategoryUpsertOne) SetSlug(v string) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateSlug() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateSlug()
	})
}

// ClearSlug clears the value of the "slug" field.
func (u *CategoryUpsertOne) ClearSlug() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearSlug()
	})
}

// SetEnabled sets the "enabled" field.
func (u *CategoryUpsertOne) SetEnabled(v bool) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateEnabled() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateEnabled()
	})
}

// ClearEnabled clears the value of the "enabled" field.
func (u *CategoryUpsertOne) ClearEnabled() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearEnabled()
	})
}

// SetIndex sets the "index" field.
func (u *CategoryUpsertOne) SetIndex(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.SetIndex(v)
	})
}

// AddIndex adds v to the "index" field.
func (u *CategoryUpsertOne) AddIndex(v uint32) *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.AddIndex(v)
	})
}

// UpdateIndex sets the "index" field to the value that was provided on create.
func (u *CategoryUpsertOne) UpdateIndex() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateIndex()
	})
}

// ClearIndex clears the value of the "index" field.
func (u *CategoryUpsertOne) ClearIndex() *CategoryUpsertOne {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearIndex()
	})
}

// Exec executes the query.
func (u *CategoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CategoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CategoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CategoryUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CategoryUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CategoryCreateBulk is the builder for creating many Category entities in bulk.
type CategoryCreateBulk struct {
	config
	builders []*CategoryCreate
	conflict []sql.ConflictOption
}

// Save creates the Category entities in the database.
func (ccb *CategoryCreateBulk) Save(ctx context.Context) ([]*Category, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Category, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CategoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ccb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CategoryCreateBulk) SaveX(ctx context.Context) []*Category {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CategoryCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Category.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CategoryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (ccb *CategoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *CategoryUpsertBulk {
	ccb.conflict = opts
	return &CategoryUpsertBulk{
		create: ccb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Category.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (ccb *CategoryCreateBulk) OnConflictColumns(columns ...string) *CategoryUpsertBulk {
	ccb.conflict = append(ccb.conflict, sql.ConflictColumns(columns...))
	return &CategoryUpsertBulk{
		create: ccb,
	}
}

// CategoryUpsertBulk is the builder for "upsert"-ing
// a bulk of Category nodes.
type CategoryUpsertBulk struct {
	create *CategoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Category.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(category.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *CategoryUpsertBulk) UpdateNewValues() *CategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(category.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Category.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *CategoryUpsertBulk) Ignore() *CategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CategoryUpsertBulk) DoNothing() *CategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CategoryCreateBulk.OnConflict
// documentation for more info.
func (u *CategoryUpsertBulk) Update(set func(*CategoryUpsert)) *CategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CategoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CategoryUpsertBulk) SetCreatedAt(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *CategoryUpsertBulk) AddCreatedAt(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateCreatedAt() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CategoryUpsertBulk) SetUpdatedAt(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *CategoryUpsertBulk) AddUpdatedAt(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateUpdatedAt() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CategoryUpsertBulk) SetDeletedAt(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *CategoryUpsertBulk) AddDeletedAt(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateDeletedAt() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetEntID sets the "ent_id" field.
func (u *CategoryUpsertBulk) SetEntID(v uuid.UUID) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetEntID(v)
	})
}

// UpdateEntID sets the "ent_id" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateEntID() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateEntID()
	})
}

// SetAppID sets the "app_id" field.
func (u *CategoryUpsertBulk) SetAppID(v uuid.UUID) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateAppID() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateAppID()
	})
}

// SetParentID sets the "parent_id" field.
func (u *CategoryUpsertBulk) SetParentID(v uuid.UUID) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetParentID(v)
	})
}

// UpdateParentID sets the "parent_id" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateParentID() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateParentID()
	})
}

// ClearParentID clears the value of the "parent_id" field.
func (u *CategoryUpsertBulk) ClearParentID() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearParentID()
	})
}

// SetName sets the "name" field.
func (u *CategoryUpsertBulk) SetName(v string) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateName() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *CategoryUpsertBulk) ClearName() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearName()
	})
}

// SetSlug sets the "slug" field.
func (u *CategoryUpsertBulk) SetSlug(v string) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateSlug() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateSlug()
	})
}

// ClearSlug clears the value of the "slug" field.
func (u *CategoryUpsertBulk) ClearSlug() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearSlug()
	})
}

// SetEnabled sets the "enabled" field.
func (u *CategoryUpsertBulk) SetEnabled(v bool) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateEnabled() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateEnabled()
	})
}

// ClearEnabled clears the value of the "enabled" field.
func (u *CategoryUpsertBulk) ClearEnabled() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearEnabled()
	})
}

// SetIndex sets the "index" field.
func (u *CategoryUpsertBulk) SetIndex(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.SetIndex(v)
	})
}

// AddIndex adds v to the "index" field.
func (u *CategoryUpsertBulk) AddIndex(v uint32) *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.AddIndex(v)
	})
}

// UpdateIndex sets the "index" field to the value that was provided on create.
func (u *CategoryUpsertBulk) UpdateIndex() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.UpdateIndex()
	})
}

// ClearIndex clears the value of the "index" field.
func (u *CategoryUpsertBulk) ClearIndex() *CategoryUpsertBulk {
	return u.Update(func(s *CategoryUpsert) {
		s.ClearIndex()
	})
}

// Exec executes the query.
func (u *CategoryUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CategoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CategoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CategoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
