apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-middleware
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cms-middleware
  template:
    metadata:
      labels:
        app: cms-middleware
    spec:
      containers:
        - name: cms-middleware
          image: uhub.service.ucloud.cn/entropypool/cms-middleware:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/CMSMiddleware
          env:
            - name: ENV_ENVIRONMENT_TARGET
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.target
            - name: ENV_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_host
            - name: ENV_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: service-config
          configMap:
            name: cms-middleware-config
            items:
              - key: service-conf
                path: CMSMiddleware.viper.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: cms-middleware
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 50840
      targetPort: 50840
    - name: grpc
      port: 50841
      targetPort: 50841
    - name: healthz
      port: 50842
      targetPort: 50842
    - name: prometheus
      port: 50843
      targetPort: 50843
  selector:
    app: cms-middleware
